"""Minimal demo script for Gemini + Google Search Grounding retrieval."""

import asyncio
import sys

from ai_search_journey.fanout import generate_fanout
from ai_search_journey.models import SearchIntent, ToolName
from ai_search_journey.planner import extract_intent
from ai_search_journey.search import search_web

DEFAULT_QUESTION = (
    "Find a coffee shop near Geekdom San Antonio for 6 people "
    "to work together, preferably quiet, and open after 8 PM."
)


def format_intent(intent: SearchIntent) -> str:
    """Format SearchIntent into a human-readable developer-demo string."""
    lines = ["PARSED INTENT", ""]

    lines.append("Search Intent:")
    if intent.intent_types:
        for it in intent.intent_types:
            label = it.value.replace("_", " ").title()
            lines.append(f"  - {label}")
    else:
        lines.append("  (none)")
    lines.append("")

    lines.append("Category:")
    lines.append(f"  {intent.category}" if intent.category else "  None")
    lines.append("")

    lines.append("Location:")
    lines.append(f"  {intent.reference_location}" if intent.reference_location else "  None")
    lines.append("")

    lines.append("Group Size:")
    lines.append(f"  {intent.group_size}" if intent.group_size is not None else "  None")
    lines.append("")

    lines.append("Open After:")
    lines.append(f"  {intent.open_after}" if intent.open_after else "  None")
    lines.append("")

    lines.append("Open Before:")
    lines.append(f"  {intent.open_before}" if intent.open_before else "  None")
    lines.append("")

    lines.append("Hard Constraints:")
    if intent.hard_constraints:
        for c in intent.hard_constraints:
            lines.append(f"  - {c}")
    else:
        lines.append("  (none)")
    lines.append("")

    lines.append("Preferences:")
    if intent.preferences:
        for p in intent.preferences:
            lines.append(f"  - {p}")
    else:
        lines.append("  (none)")
    lines.append("")

    lines.append("Requested Results:")
    lines.append(f"  {intent.requested_result_count}")

    return "\n".join(lines)


async def main() -> None:
    question = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_QUESTION
    print("\n--- GOOGLE SEARCH GROUNDING DEMO ---\n")
    print(f"QUESTION:\n{question}\n")

    try:
        intent = await extract_intent(question)
        print(format_intent(intent))
        print()

        fanout = await generate_fanout(intent)
        print("PLANNER FAN-OUT:")
        for idx, q in enumerate(fanout, start=1):
            print(f"\n{idx}. [{q.tool.value.upper()}]")
            print(f"   Goal:   {q.goal}")
            print(f"   Query:  {q.query}")
            if q.reason:
                print(f"   Reason: {q.reason}")
        print()

        search_tasks = [q for q in fanout if q.tool == ToolName.GOOGLE_SEARCH]
        print(f"Executing {len(search_tasks)} Google Search Grounding task(s)...\n")

        if not search_tasks:
            print("No google_search tasks generated by planner.")
            return

        print("=" * 60)
        print("SEARCH GROUNDING TASKS EXECUTED")
        print("=" * 60)

        for idx, task in enumerate(search_tasks, start=1):
            print(f"\nTASK {idx}")
            print("-" * 40)
            print(f"Planner Goal:   {task.goal}")
            print(f"Planner Query:  {task.query}")
            if task.reason:
                print(f"Planner Reason: {task.reason}")
            print()

            result = await search_web(task)

            print("Executed Google Search Queries:")
            if result.executed_search_queries:
                for q in result.executed_search_queries:
                    print(f"  - {q}")
            else:
                print("  (none recorded)")
            print()

            print("Grounded Findings:")
            print(result.grounded_text.strip())
            print()

            print("Sources:")
            if result.sources:
                for s_idx, s in enumerate(result.sources, start=1):
                    print(f"  {s_idx}. {s.title or 'Web Source'}")
                    print(f"     {s.url}")
            else:
                print("  (none recorded)")
            print()

            print("Citation Supports:")
            if result.citations:
                for c in result.citations:
                    source_str = (
                        f"source index: {c.source_indices}"
                        if c.source_indices
                        else "no sources linked"
                    )
                    if c.cited_text:
                        print(f"  - \"{c.cited_text.strip()}\" ({source_str})")
                    else:
                        print(
                            f"  - Segment [{c.start_index}:{c.end_index}] ({source_str})"
                        )
            else:
                print("  (none recorded)")
            print("-" * 60)

    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
