"""AI Visibility (V3) domain models, enums, and deterministic observation extractor."""

from ai_search_journey.visibility.bigquery_repository import (
    BigQueryDependencyError,
    BigQueryVisibilityRepository,
    BigQueryWriteError,
)
from ai_search_journey.visibility.bigquery_schema import (
    ALL_TABLES,
    LOCK_KEY_BUNDLE_WRITE,
    TABLE_BRAND_OBSERVATIONS,
    TABLE_BUNDLE_PAYLOADS,
    TABLE_CITATIONS,
    TABLE_FANOUT_OBSERVATIONS,
    TABLE_REPOSITORY_LOCKS,
    TABLE_VISIBILITY_SCANS,
    InvalidIdentifierError,
    calculate_bundle_sha256,
    get_repository_locks_ddl,
    get_repository_locks_seed_dml,
    get_schema_ddl_statements,
    get_schema_seed_statements,
    serialize_bundle_canonically,
    validate_dataset_id,
    validate_location,
    validate_project_id,
)
from ai_search_journey.visibility.extractor import (
    AmbiguousBrandMatchError,
    build_answer_mention_corpus,
    extract_brand_mentions,
    extract_visibility_scan_bundle,
    match_candidate_to_brand,
)
from ai_search_journey.visibility.metrics import (
    VisibilityTrendPoint,
    calculate_competitor_comparison,
    calculate_visibility_metrics,
    calculate_visibility_trend,
)
from ai_search_journey.visibility.models import (
    BrandObservation,
    BrandProfile,
    BrandRole,
    CitationObservation,
    FanoutObservation,
    PromptDefinition,
    ScanStatus,
    VisibilityMetrics,
    VisibilityProject,
    VisibilityScan,
    VisibilityScanBundle,
    normalize_domain,
)
from ai_search_journey.visibility.repository import (
    DuplicateScanError,
    InMemoryVisibilityRepository,
    InvalidRepositoryFilterError,
    VisibilityRepository,
)
from ai_search_journey.visibility.runner import (
    IncompleteJourneyError,
    InconsistentScanError,
    VisibilityRunnerError,
    VisibilityScanResult,
    run_visibility_scan,
)
from ai_search_journey.visibility.ui import render_visibility_tab

__all__ = [
    "ALL_TABLES",
    "AmbiguousBrandMatchError",
    "BigQueryDependencyError",
    "BigQueryVisibilityRepository",
    "BigQueryWriteError",
    "BrandObservation",
    "BrandProfile",
    "BrandRole",
    "CitationObservation",
    "DuplicateScanError",
    "FanoutObservation",
    "InMemoryVisibilityRepository",
    "IncompleteJourneyError",
    "InconsistentScanError",
    "InvalidIdentifierError",
    "InvalidRepositoryFilterError",
    "LOCK_KEY_BUNDLE_WRITE",
    "PromptDefinition",
    "ScanStatus",
    "TABLE_BRAND_OBSERVATIONS",
    "TABLE_BUNDLE_PAYLOADS",
    "TABLE_CITATIONS",
    "TABLE_FANOUT_OBSERVATIONS",
    "TABLE_REPOSITORY_LOCKS",
    "TABLE_VISIBILITY_SCANS",
    "VisibilityMetrics",
    "VisibilityProject",
    "VisibilityRepository",
    "VisibilityRunnerError",
    "VisibilityScan",
    "VisibilityScanBundle",
    "VisibilityScanResult",
    "VisibilityTrendPoint",
    "build_answer_mention_corpus",
    "calculate_bundle_sha256",
    "calculate_competitor_comparison",
    "calculate_visibility_metrics",
    "calculate_visibility_trend",
    "extract_brand_mentions",
    "extract_visibility_scan_bundle",
    "get_repository_locks_ddl",
    "get_repository_locks_seed_dml",
    "get_schema_ddl_statements",
    "get_schema_seed_statements",
    "match_candidate_to_brand",
    "normalize_domain",
    "render_visibility_tab",
    "run_visibility_scan",
    "serialize_bundle_canonically",
    "validate_dataset_id",
    "validate_location",
    "validate_project_id",
]
